"""add google oauth columns to users

Revision ID: 1f34842077fe
Revises: 46131eb63191
Create Date: 2026-09-26 20:13:22.871699

"""
from alembic import op
import sqlalchemy as sa


revision = '1f34842077fe'
down_revision = '46131eb63191'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_refresh_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('google_access_token', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('google_token_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('google_connected', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_connected')
    op.drop_column('users', 'google_token_expiry')
    op.drop_column('users', 'google_access_token')
    op.drop_column('users', 'google_refresh_token')
    # ### end Alembic commands ###
