"""add sub_niche to workspaces

Revision ID: 46131eb63191
Revises: 49029d63849e
Create Date: 2026-09-26 18:59:42.952877

"""
from alembic import op
import sqlalchemy as sa


revision = '46131eb63191'
down_revision = '49029d63849e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('sub_niche', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'sub_niche')
    # ### end Alembic commands ###
