"""Add location and competitors to workspace

Revision ID: 49029d63849e
Revises: 0002
Create Date: 2026-09-26 18:42:19.525612

"""
from alembic import op
import sqlalchemy as sa


revision = '49029d63849e'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('location', sa.String(length=120), nullable=True))
    op.add_column('workspaces', sa.Column('competitors', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'competitors')
    op.drop_column('workspaces', 'location')
    # ### end Alembic commands ###
